### ISSUE TITLE
CRITICAL - A-4 insta-explodes on spawn in OpenBeta 2.5.4.27314

### ISSUE THREAD

**Issue by callmepartario** [Merker6/community-a4e-c#101]
Looks like a LUA / 3-D fix needed, see:

![image](https://user-images.githubusercontent.com/17432407/52749575-96fa0880-2fb7-11e9-842f-aebcbdd5daab.png)

Happy to test when this is resolved and discuss release of the fix.

**Comment by callmepartario** [comment]
update, see: https://forums.eagle.ru/showpost.php?p=3800261&postcount=7

**Comment by heclak** [comment]
This is fixed in OpenBeta 2.5.4.28090
