### ISSUE TITLE
BUG - MK-82 on MER Pylon 3 no release

### ISSUE THREAD

**Issue by DISCOVMA131** [Merker6/community-a4e-c#104]
2 different aircraft, same multiplayer server, no release of 6xMK-82 on MER, Pylon 3 - doublechecked switchology, Master Arm ON, BOMBS, Pylon up, AWRS ON, RIPPPLE-PAIRS (tried RIPPLE-SINGLE, and SALVO-PAIRS).

Same flight, 4xMK-20's released as set, Zuni's released as set, 20mm MK-12 cannons worked.

Multiplayer, on NTTR.

Same loadout and settings on local machine releases fine IF set for SINGLE only.

**Comment by DISCOVMA131** [comment]
ADDITIONAL INFO:
Verified on a different MP server, no release when set STEP-PAIRS for 6xMK-82 on MER on Pylon 3, but good release on STEP-PAIRS for 2xMK-82 on TER on Pylons 2 and 4.

6xMK-82 on MER on Pylon 3 did drop fine on STEP-SINGLE

**Comment by heclak** [comment]
Station 3 should/will not release in STEP PAIRS or RIPPLE PAIRS. This is the correct function of the aircraft. Valid station pairs are 1-5 and 2-4. There are no warning tones or lights, NATOPS expect pilots to know this behaviour.

Station 3 will release on SINGLE and SALVO modes (STEP/RIPPLE).

Weapon system behaviour is documented in my guide.
https://docs.google.com/presentation/d/1cUH7jpAoGHm-IzUDnv_NDhiZlvX55Q9WvpgR1d9ksYY/edit?usp=sharing
