### ISSUE TITLE
Interior Red Lights Don't Turn Off 

### ISSUE THREAD

**Issue by Merker6** [Merker6/community-a4e-c#11]
Version: 1.02

Description: Possibly related to issue #10 , the Red Lights are unable to turn off. As with #10, this bug has existed since implementation.

**Comment by heclak** [comment]
I'm wondering if this is a bug at all. From what I read in the NATOPS, it seems the red lights would always be on, just with three level changes (dim/medium/bright). I tried asking JazAero but he doesn't know the lights well enough. We'll need to find someone who flew the A-4E enough to remember how it works. But if someone can confirm the operation, I can fix the code easily.

**Comment by heclak** [comment]
#20 This is fixed in this pull request.
