### ISSUE TITLE
Request: Parking Brake or Chalks

### ISSUE THREAD

**Issue by Merker6** [Merker6/community-a4e-c#12]
Standing Request from Merker

The A-4 is in dire need of the ability to cold-start from a carrier deck. Implementing a Parking Brake or Chalks would enable the aircraft to both cold start and refit on the deck of a carrier.

**Comment by heclak** [comment]
I've managed to add functional chocks to the A-4E. Just missing the visual assets.

Currently working on init code to load the aircraft with chocks on when birth == GROUND_COLD

**Comment by LevelPulse** [comment]
@heclak Is it possible to show an animation arg when functional chocks are in place? Like when the A-4 has certain parameters the huffer is shown.

**Comment by heclak** [comment]
@LevelPulse Yes. I've tested it using the huffer animation.
