### ISSUE TITLE
Canopy invisible whilst open (Inside View)

### ISSUE THREAD

**Issue by LevelPulse** [Merker6/community-a4e-c#2]
Mod Version: 1.02
Description:  When the canopy is fully open, it is not visible from cockpit view.

**Comment by heclak** [comment]
#20 Fixed in this pull request

**Comment by LevelPulse** [comment]
Fix: bugfix/canopy-and-lighting-fixes
Pull Request: #21

Awaiting for branch to be merged before being closed.

**Comment by LevelPulse** [comment]
Merged.
