### ISSUE TITLE
3D: Emergency Generator Deploy animation is bugged

### ISSUE THREAD

**Issue by LevelPulse** [Merker6/community-a4e-c#30]
When pressing the emergency generator deploy handle, the animation in F2 view is retracting in and out. Textures also look out of place.

![image](https://user-images.githubusercontent.com/7634418/50983498-7b529c80-14f7-11e9-9a67-5253112a8e26.png)
![image](https://user-images.githubusercontent.com/7634418/50983552-94f3e400-14f7-11e9-87c3-7cb78764109f.png)
![image](https://user-images.githubusercontent.com/7634418/50983559-9ae9c500-14f7-11e9-87e0-26c3cc7e519c.png)

**Comment by heclak** [comment]
I have the code fixed for the animation but will need help with the texture/model of the fan blade. 

There's a todo in the code.

> TODO revise this when we have anim args for blades that already look like they're spinning (blurred in spin direction). This will be necessary to make it look better as well as avoid aliasing effects at certain speeds

**Comment by heclak** [comment]
The animation is fixed and merged into 1.03. Texture will be left in another issue.
