### ISSUE TITLE
Wheel brakes need to be strengthened.

### ISSUE THREAD

**Issue by JazAero** [Merker6/community-a4e-c#32]
Wheel brakes on the aircraft are currently extremely weak and lead to overruns and poor steering, even at low speeds.  The actual aircraft had very powerful multi-rotor disc brakes that could lock up even under high speed landing passes which is published in the natops as a caution for pilots not to overbrake.  So as not to shred the tires.

**Comment by NeroDCS** [comment]
i looked at the NATOP (A-4E/F) on page '1-33'. it says the plane has only single disc breaks. Are we using differen manuals? 

NAVAIR 01-40AVC-1
NATOPS FLIGHT MANUAL
navy model
A-4E/F

**Comment by JazAero** [comment]
You are correct, it is a single disc rotor but it is an extremely beefy one with triple hydraulic pistons, which made it very powerful.  That aircraft could lock it breaks up even on a hot landing.

**Comment by NeroDCS** [comment]
yes,a table with break data would be really nice

**Comment by LevelPulse** [comment]
@NeroDCS Has this issue been resolved? If i recall correctly in the test you had last night someone mentioned the brakes being stronger? If this is the case, close the issue.

**Comment by callmepartario** [comment]
agree, this issue can be closed.
