### ISSUE TITLE
Invisible CBU pod in x2 configuration

### ISSUE THREAD

**Issue by LevelPulse** [Merker6/community-a4e-c#4]
Version: 1.02
Description: CBU pods on inner wing pylons are invisible when loaded in their x2 configuration.

**Comment by hectorlee** [comment]
Been testing this out. When loading a x2 config, an error in loading the spec map appears in the logs. Might just need to remove the spec map from the 3d model since there are PBR textures.

**Comment by heclak** [comment]
Been testing this out. When loading a x2 config, an error in loading the spec map appears in the logs. Might just need to remove the spec map from the 3d model since there are PBR textures.

**Comment by heclak** [comment]
I've solved this with a change in the declaration of the loadouts. x2 config is visible and functional now. Will upload the code when there is a way to do so.

Currently working on getting the bomblets to slide out the rear tubes instead of dropping downwards directly.

**Comment by LevelPulse** [comment]
You can post the snipped through here.

**Comment by heclak** [comment]
Here is the corrected A4E_Weapons.lua file. 

Changelog: 

- Fixed visibility issue with dual CBU launchers.
- Corrected release position of bomblets from SUU-7 launcher to end of launcher tubes.
- Corrected visual representation of bomblets in tubes. Bomblets are now visible in all tubes when loaded and tubes will be empty when expended.

[A4E_Weapons.zip](https://github.com/Merker6/community-a4e-c/files/2708790/A4E_Weapons.zip)

**Comment by LevelPulse** [comment]
Change is under pull request and waiting for Merker's approval before submitted into branch 1.03

**Comment by heclak** [comment]
I just checked the 1.03 branch and the A4E_Weapons.lua file isn't the one I uploaded here. I'll upload the code on a branch so it easier to see the code diff for you.

**Comment by heclak** [comment]
I've created a pull request with the required fixes. #18
