### ISSUE TITLE
DCS Crash when starting from Nellis AFB

### ISSUE THREAD

**Issue by heclak** [Merker6/community-a4e-c#42]
**From Google Forms**

Placing the aircraft at Nellis, setting the starting state to (takeoff from ramp)/cold start, when initializing, the bar loads approximately 75% of the way and simply stops, no CTD, nothing, CPU ACTY light does not indicate anything. I cannot even pull up tskmgr to take care of it as a DCS splash screen blocks any windows from topping it.

**Comment by DISCOVMA131** [comment]
Have duplicated this multiple times - cannot start from Nellis hot or cold - thought it had been previously reported

**Comment by DISCOVMA131** [comment]
This appears to have cleared up and is no longer an issue.

**Comment by LevelPulse** [comment]
Tested on DCS 2.5.4 on Nellis AFB, from ramp.

Working now as of version 1.03 branch. Issue is now closed.

![image](https://user-images.githubusercontent.com/7634418/52540421-223d8900-2d81-11e9-9aa5-094fc6ff500f.png)
