### ISSUE TITLE
2nd Clock on Canopy Frame, Second Hand Not Moving

### ISSUE THREAD

**Issue by DISCOVMA131** [Merker6/community-a4e-c#43]
As in title, the second hand of the clock on the canopy frame by the standby compass does not move - hours and minutes hands are functioning correctly

**Comment by heclak** [comment]
This is not a bug. There are 4 hands on the clock on the canopy frame. Two hands for the current time (hours and minutes) and two thinner hands for the stopwatch (mins and seconds). Press the button on the top right to start, stop, reset the timer.
