### ISSUE TITLE
Suspension code is going through floor.

### ISSUE THREAD

**Issue by LevelPulse** [Merker6/community-a4e-c#49]
[https://youtu.be/p6Q0tW1d1m8?t=1017](https://youtu.be/p6Q0tW1d1m8?t=1017)

Refer to this timestamped video that shows the A-4E landing and the wheels going into the ground.

![image](https://user-images.githubusercontent.com/7634418/51576061-a3091380-1eac-11e9-8883-82278ad5e492.png)

**Comment by NeroDCS** [comment]
1) what airport?
2) Multiplay/singleplay?
3) i assume 1.03?

**Comment by LevelPulse** [comment]
1. no idea
2. multiplayer
3. 1.02

**Comment by NeroDCS** [comment]
i further assume you were a client, the its probably standart DCS issue. Just tested multiplaye as a server (1.03) and suspension is fine

**Comment by heclak** [comment]
Looking at the part of the video just before that. I'm suspecting the external view is actually from a replay since the landing was initially done from inside the cockpit. Maybe the replay code is the one that is broken?
