### ISSUE TITLE
Damage Model immune to SAM

### ISSUE THREAD

**Issue by LevelPulse** [Merker6/community-a4e-c#5]
Version: 1.02
Description: Plane is still immune to SAM damage

**Comment by Merker6** [comment]
It should be noted that this is in specific cases. Gameplay testing using my desktop has show consistent hits registered on the A-4 using S-400 system. SA-2 in-game doesn't fair too well against the AI, as the Chaff easily defeats it

**Comment by heclak** [comment]
This will be fixed with the new damage model
