### ISSUE TITLE
Carrier Spawn - Collision Issue other Aircraft

### ISSUE THREAD

**Issue by DISCOVMA131** [Merker6/community-a4e-c#58]
On our MP server it has been observed that the Scooter initially moves around a lot on initial spawn in, to the point it damages other aircraft although not always the Scooter itself - even if the other aircraft are not adjacent to the Scooter.

Wonder if birth state with chocks enabled will address this?

We can try to document this for more\better info.

**Comment by NeroDCS** [comment]
is this movement along the normal movement axis eg. forward/backwards?
or is its sliding across the deck left and right?

**Comment by NeroDCS** [comment]
this issue is also present in other planes (was observed in my squadron with the FA18)
i assume it has to do with the loading of the Textures, a work around could be to spawn into a land based A4 first and then switch to the Carrier slot.

**Comment by DISCOVMA131** [comment]
Some initial testing at CSG-1 on private MP server:

1. loaded in al dahfra, then to stennis, success
2. relogged in, straight to stennis, crash to desktop
3. rejoined, started al dahfra, reslotted stennis success
4. without rejoining after 3., back to spectators reslotted to stennis, success
5. repeated 4, launched off the deck into water immediately.
6. repeated 4, crash to desktop.

Sounds a little to me like the offset VR clickpoint issue in that spawning in, out and then back in seems to improve stability, if you only do it once or twice.
