### ISSUE TITLE
Missing Snapviews

### ISSUE THREAD

**Issue by heclak** [Merker6/community-a4e-c#70]
Forum user brought up the point of snapviews missing in the module config. Someone could look into what standard views are in the other modules and include them for the A-4.

**Comment by LevelPulse** [comment]
I've assigned myself this and will sort!

**Comment by mwlue** [comment]
@heclak , thanks for adding this.   Orzz

**Comment by LevelPulse** [comment]
Upon more investigation, snap views are working fine, although they aren't "standard" in that they are snap views to look out of the cockpit. Modules such as the Viggen/MiG etc use snap views for certain parts of the cockpit? 

Is this something we want or not?

**Comment by heclak** [comment]
@LevelPulse I thought you were updating the snap views the other day? So everything is actually in order? What are the snapviews in ED's modules? Just for looking out or at parts of the cockpit too.
