### ISSUE TITLE
Shrike needs a lock tone before firing

### ISSUE THREAD

**Issue by heclak** [Merker6/community-a4e-c#75]
Shrike should have a lock tone to determine the direction of fire before releasing the weapon.

**Comment by DISCOVMA131** [comment]
I think Nero had offered to setup a Shrike API to provide search and lock tones similar to Sidearm and Sidearm - if not I would try and figure out how to repurpose existing tones for same

**Comment by heclak** [comment]
@DISCOVMA131 I'm actually writing the code for this right now.

**Comment by heclak** [comment]
Feature completed with pull request #86
