### ISSUE TITLE
Missing netcode argument for nosewheel steering

### ISSUE THREAD

**Issue by heclak** [Merker6/community-a4e-c#84]
Need to add netcode argument for nosewheel angle/position

**Comment by LevelPulse** [comment]
This has been added to bugfix/wheel-chocks-netcode with animation arg #2 used, although needs to be tested in multiplayer.

**Comment by LevelPulse** [comment]
Issue is sorted and waiting for pull request approval #93

**Comment by heclak** [comment]
issue resolved with pull request #93
