### ISSUE TITLE
LIGHTING - ECM Monitor Panel

### ISSUE THREAD

**Issue by DISCOVMA131** [Merker6/community-a4e-c#88]
For the ECM Monitor Panel, the red lighting texture should NOT be applied to the 2 switchlights (3-segment TEST and 4-segment ALQ),  The switchlights should be pure colors with no pink\red washout.

Recommend GO on the 3-segment TEST light be changed to Green unless there is NATOPS guidance it was amber.

**Comment by callmepartario** [comment]
Setup should match the construction of the dash lamps and APC and this issue should be resolved - textures are all set up!

see: https://cdn.discordapp.com/attachments/543940775583416368/544203329664712704/unknown.png

**Comment by heclak** [comment]
Seems to fixed in v1.3.
